import { Router } from 'express';
import { z } from 'zod';
import { randomBytes, createHash, randomUUID } from 'node:crypto';
import rateLimit from 'express-rate-limit';
import { database } from '@rda/database';
import { AuthService } from '../auth/auth-service.js';
import { requireAuth, requireRole, csrfProtection, audit } from '../middleware/auth.js';
import type { Logger } from 'pino';

const credentials = z.object({ email: z.email(), password: z.string().min(12).max(200) });
const cookieOptions = { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax' as const, path: '/' };
export const authRouter = (logger: Logger) => { const router = Router(); const service = new AuthService(database); const limiter = rateLimit({ windowMs: 15 * 60_000, limit: 10, standardHeaders: true, legacyHeaders: false });
  router.post('/register', limiter, async (req, res, next) => { try { const body = z.object({ ...credentials.shape, displayName: z.string().min(1).max(100), organizationName: z.string().min(1).max(120), restaurantName: z.string().min(1).max(120) }).parse(req.body); const result = await service.register(body); const session = await service.createSession(result.userId); res.cookie('rda_session', session.token, cookieOptions); res.cookie('rda_csrf', randomBytes(24).toString('base64url'), { ...cookieOptions, httpOnly: false }); res.status(201).json({ data: result }); } catch (error) { next(error); } });
  router.post('/login', limiter, async (req, res, next) => { try { const body = credentials.parse(req.body); const user = await service.authenticate(body.email, body.password); const session = await service.createSession(user.id); res.cookie('rda_session', session.token, cookieOptions); res.cookie('rda_csrf', randomBytes(24).toString('base64url'), { ...cookieOptions, httpOnly: false }); logger.info({ userId: user.id, requestId: req.id }, 'login'); res.json({ data: { userId: user.id, sessionId: session.sessionId } }); } catch (error) { next(error); } });
  router.post('/logout', requireAuth, csrfProtection, audit(logger, 'LOGOUT'), async (req, res, next) => { try { await service.revokeSession(req.tenant!.sessionId); res.clearCookie('rda_session', cookieOptions); res.status(204).send(); } catch (error) { next(error); } });
  router.post('/logout-all', requireAuth, csrfProtection, audit(logger, 'LOGOUT_ALL'), async (req, res, next) => { try { await service.revokeAllSessions(req.tenant!.userId); res.clearCookie('rda_session', cookieOptions); res.status(204).send(); } catch (error) { next(error); } });
  router.get('/me', requireAuth, (_req, res) => res.json({ data: _req.tenant }));
  router.post('/members/invite', requireAuth, requireRole('OWNER'), csrfProtection, audit(logger, 'INVITE'), async (req, res, next) => { try { const body = z.object({ email: z.email(), role: z.enum(['MANAGER', 'VIEWER']), branchId: z.uuid().optional() }).parse(req.body); if (body.branchId && !req.tenant!.permittedBranchIds.includes(body.branchId)) return res.status(403).json({ error: { code: 'BRANCH_FORBIDDEN' } }); const token = randomBytes(32).toString('base64url'); const invitation = await database.invitation.create({ data: { id: randomUUID(), organizationId: req.tenant!.organizationId, restaurantId: req.tenant!.restaurantId, branchId: body.branchId, email: body.email.toLowerCase(), role: body.role, tokenHash: createHash('sha256').update(token).digest('hex'), invitedById: req.tenant!.userId, expiresAt: new Date(Date.now() + 7 * 86_400_000) } }); res.status(201).json({ data: { invitationId: invitation.id, token } }); } catch (error) { next(error); } });
  router.post('/invitations/accept', requireAuth, csrfProtection, audit(logger, 'INVITATION_ACCEPT'), async (req, res, next) => { try { const body = z.object({ token: z.string().min(20) }).parse(req.body); const invitation = await database.invitation.findFirst({ where: { tokenHash: createHash('sha256').update(body.token).digest('hex'), acceptedAt: null, expiresAt: { gt: new Date() }, organizationId: req.tenant!.organizationId, restaurantId: req.tenant!.restaurantId } }); if (!invitation) return res.status(400).json({ error: { code: 'INVITATION_INVALID' } }); const user = await database.user.findUniqueOrThrow({ where: { id: req.tenant!.userId } }); if (user.email !== invitation.email) return res.status(403).json({ error: { code: 'INVITATION_EMAIL_MISMATCH' } }); await database.$transaction([database.membership.create({ data: { organizationId: invitation.organizationId, restaurantId: invitation.restaurantId, branchId: invitation.branchId, userId: user.id, role: invitation.role } }), database.invitation.update({ where: { id: invitation.id }, data: { acceptedAt: new Date() } })]); res.status(204).send(); } catch (error) { next(error); } }); return router; };
